#!/usr/bin/env ruby

arg = ARGV[0]

if arg == ''
 puts RUBY_PLATFORM
elsif arg == '-name'
 puts RUBY_PLATFORM.split('-')[-1].capitalize
elsif arg == '-arch'
 puts RUBY_PLATFORM.split('-')[0]
else
 puts RUBY_PLATFORM
end
